// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-restaurant-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function resolveRestaurant(ctx) {
  const supabase = supabaseForUser(ctx);
  const userId = ctx.getUserId();
  const { data, error } = await supabase.from("profiles").select("restaurant_id").eq("id", userId).maybeSingle();
  if (error) throw new Error(error.message);
  const restaurantId = data?.restaurant_id;
  if (!restaurantId) throw new Error("No restaurant is linked to this account.");
  return { supabase, restaurantId };
}
function textResult(payload, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}

// src/lib/mcp/tools/get-restaurant-overview.ts
var get_restaurant_overview_default = defineTool({
  name: "get_restaurant_overview",
  title: "Get restaurant overview",
  description: "Return the restaurant linked to the signed-in account, with today's order count and revenue.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    try {
      const { supabase, restaurantId } = await resolveRestaurant(ctx);
      const { data: restaurant, error } = await supabase.from("restaurants").select("id, name, address, phone, email").eq("id", restaurantId).maybeSingle();
      if (error) return errorResult(error.message);
      const startOfDay = /* @__PURE__ */ new Date();
      startOfDay.setHours(0, 0, 0, 0);
      const { data: orders, error: ordersError } = await supabase.from("orders").select("total").eq("restaurant_id", restaurantId).gte("created_at", startOfDay.toISOString());
      if (ordersError) return errorResult(ordersError.message);
      const todayRevenue = (orders ?? []).reduce(
        (sum, o) => sum + Number(o.total ?? 0),
        0
      );
      const payload = {
        restaurant,
        today: { orders: orders?.length ?? 0, revenue: Math.round(todayRevenue * 100) / 100 }
      };
      return textResult(payload, payload);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-recent-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_recent_orders_default = defineTool2({
  name: "list_recent_orders",
  title: "List recent orders",
  description: "List the most recent orders for the signed-in user's restaurant, newest first. Optionally filter by status.",
  inputSchema: {
    limit: z.number().int().optional().describe("How many orders to return (1-50, default 10)."),
    status: z.string().optional().describe("Optional order status filter, e.g. 'pending', 'completed'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    try {
      const { supabase, restaurantId } = await resolveRestaurant(ctx);
      const take = Math.min(Math.max(Math.trunc(limit ?? 10), 1), 50);
      let query = supabase.from("orders").select(
        "id, order_number, customer_name, items, total, status, payment_status, payment_method, order_type, source, created_at"
      ).eq("restaurant_id", restaurantId).order("created_at", { ascending: false }).limit(take);
      if (status) query = query.eq("status", status);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return textResult(data ?? [], { orders: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/get-sales-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_sales_summary_default = defineTool3({
  name: "get_sales_summary",
  title: "Get sales summary",
  description: "Summarise sales for the signed-in user's restaurant over the last N days: revenue, order count, average order value, and a per-day breakdown.",
  inputSchema: {
    days: z2.number().int().optional().describe("Number of days to look back (1-90, default 7).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    try {
      const { supabase, restaurantId } = await resolveRestaurant(ctx);
      const window = Math.min(Math.max(Math.trunc(days ?? 7), 1), 90);
      const since = /* @__PURE__ */ new Date();
      since.setHours(0, 0, 0, 0);
      since.setDate(since.getDate() - (window - 1));
      const { data, error } = await supabase.from("orders").select("total, created_at, payment_method").eq("restaurant_id", restaurantId).gte("created_at", since.toISOString());
      if (error) return errorResult(error.message);
      const rows = data ?? [];
      const byDay = {};
      let revenue = 0;
      for (const row of rows) {
        const amount = Number(row.total ?? 0);
        revenue += amount;
        const day = String(row.created_at).slice(0, 10);
        byDay[day] = byDay[day] ?? { orders: 0, revenue: 0 };
        byDay[day].orders += 1;
        byDay[day].revenue = Math.round((byDay[day].revenue + amount) * 100) / 100;
      }
      const payload = {
        period_days: window,
        from: since.toISOString().slice(0, 10),
        orders: rows.length,
        revenue: Math.round(revenue * 100) / 100,
        average_order_value: rows.length ? Math.round(revenue / rows.length * 100) / 100 : 0,
        by_day: Object.entries(byDay).sort(([a], [b]) => a.localeCompare(b)).map(([date, stats]) => ({ date, ...stats }))
      };
      return textResult(payload, payload);
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-menu-items.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_menu_items_default = defineTool4({
  name: "list_menu_items",
  title: "List menu items",
  description: "List menu items for the signed-in user's restaurant, optionally filtered by category or a name search.",
  inputSchema: {
    category: z3.string().optional().describe("Exact category name to filter by."),
    search: z3.string().optional().describe("Case-insensitive substring match on the item name."),
    limit: z3.number().int().optional().describe("How many items to return (1-100, default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    try {
      const { supabase, restaurantId } = await resolveRestaurant(ctx);
      const take = Math.min(Math.max(Math.trunc(limit ?? 50), 1), 100);
      let query = supabase.from("menu_items").select("id, name, category, price, is_available, is_veg, is_special, description").eq("restaurant_id", restaurantId).order("category", { ascending: true }).limit(take);
      if (category) query = query.eq("category", category);
      if (search) query = query.ilike("name", `%${search}%`);
      const { data, error } = await query;
      if (error) return errorResult(error.message);
      return textResult(data ?? [], { items: data ?? [] });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/tools/list-low-stock-inventory.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_low_stock_inventory_default = defineTool5({
  name: "list_low_stock_inventory",
  title: "List low stock inventory",
  description: "List inventory items for the signed-in user's restaurant that are at or below their reorder level.",
  inputSchema: {
    limit: z4.number().int().optional().describe("How many items to return (1-100, default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
    try {
      const { supabase, restaurantId } = await resolveRestaurant(ctx);
      const take = Math.min(Math.max(Math.trunc(limit ?? 50), 1), 100);
      const { data, error } = await supabase.from("inventory_items").select("id, name, category, quantity, unit, reorder_level, cost_per_unit").eq("restaurant_id", restaurantId).order("quantity", { ascending: true }).limit(500);
      if (error) return errorResult(error.message);
      const low = (data ?? []).filter((item) => Number(item.quantity ?? 0) <= Number(item.reorder_level ?? 0)).slice(0, take);
      return textResult(low, { items: low });
    } catch (e) {
      return errorResult(e instanceof Error ? e.message : String(e));
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "clmsoetktmvhazctlans";
var mcp_default = defineMcp({
  name: "tasty-bite-harbor",
  title: "tasty-bite-harbor",
  version: "0.1.0",
  instructions: "Tools for the tasty-bite-harbor restaurant POS. Every tool acts as the signed-in user and is scoped to their restaurant. Use `get_restaurant_overview` for today's snapshot, `list_recent_orders` and `get_sales_summary` for order and revenue analysis, `list_menu_items` for the menu, and `list_low_stock_inventory` for restocking decisions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_restaurant_overview_default,
    list_recent_orders_default,
    get_sales_summary_default,
    list_menu_items_default,
    list_low_stock_inventory_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
