
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { Json } from './types';

const SUPABASE_URL = "https://clmsoetktmvhazctlans.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbXNvZXRrdG12aGF6Y3RsYW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MTE5NTIsImV4cCI6MjA1NDA4Nzk1Mn0.4j8CLdQn9By5XawbdC4LlWhFumIQT6gqCl2lZnQwQWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add explicit type for room_food_orders to help with TypeScript errors
export type RoomFoodOrder = {
  id: string;
  room_id: string;
  restaurant_id: string;
  customer_name: string;
  items: Json;
  total: number;
  status: string;
  created_at: string;
  updated_at: string;
}

// Order item type that we'll need to convert to Json
export type OrderItem = {
  id: string;
  menuItemId: string;
  name: string;
  price: number;
  quantity: number;
}

// Type for reservation with special occasion
export type ReservationWithSpecialOccasion = {
  id: string;
  customer_name: string;
  customer_email: string | null;
  customer_phone: string | null;
  room_id: string;
  start_time: string;
  end_time: string;
  status: string | null;
  notes: string | null;
  special_occasion: string | null;
  special_occasion_date: string | null;
  marketing_consent: boolean;
}

// Type for promotion campaigns
export type PromotionCampaign = {
  id: string;
  restaurant_id: string;
  name: string;
  description: string | null;
  start_date: string;
  end_date: string;
  discount_percentage: number;
  discount_amount: number;
  promotion_code: string | null;
  created_at: string;
  updated_at: string;
}

// Type for sent promotions
export type SentPromotion = {
  id: string;
  restaurant_id: string;
  customer_name: string;
  customer_email: string | null;
  customer_phone: string;
  reservation_id: string | null;
  promotion_id: string | null;
  sent_date: string;
  sent_status: string;
  sent_method: string;
}
